---
- name: Install dependencies
  apt:
    pkg: "apt-transport-https"
    state: present

- name: Check if i2p router is already installed
  stat:
    path: "{{ i2p_install_path }}/i2prouter"
  register: i2prouter

- name: "Create i2p user: {{ i2p_user }}"
  user:
    name: "{{ i2p_user }}"
    state: present
    createhome: true

- include_tasks:
    file: apt_add.yml

- name: Install i2p
  apt:
    pkg:
      - "i2p"
      - "i2p-keyring"
    update_cache: true
  when: not i2prouter.stat.exists

- name: Generate i2p router service file
  template:
    src: templates/i2p-router.service.jinja
    dest: /etc/systemd/system/i2p-router.service
  notify: Reload systemd-daemon


- name: Start and enable i2p router
  service:
    name: "i2p-router"
    state: started
    enabled: true
