---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "apt-transport-https"

- name: check if I2P router already installed
  stat:
    path: "{{ i2p_install_path }}/i2prouter"
  register: i2prouter

- name: "Create i2p user: {{ i2p_user }}"
  user:
    name: "{{ i2p_user }}"
    state: present

- include_tasks:
    file: apt_add.yml

- name: Install i2p
  apt:
    pkg:
      - "i2p"
      - "i2p-keyring"
    update_cache: true
  when: not i2prouter.stat.exists

- name: generate I2P router service file
  template:
    src: ../templates/i2p-router.service.j2
    dest: /etc/systemd/system/i2p-router.service
  when: not i2prouter.stat.exists
  register: service_file

- name: systemd daemon-reload
  service: daemon_reload=yes
  when: service_file is defined

- name: Start and enable i2p router
  service:
    name: "i2p-router"
    state: started
    enabled: true
